//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.04 at 01:20:28 PM GMT 
//


package repr.models;

import ae.javax.xml.bind.JAXBElement;
import ae.javax.xml.bind.annotation.XmlElementDecl;
import ae.javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the repr.models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Tournament_QNAME = new QName("models.repr", "Tournament");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: repr.models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Tournament }
     * 
     */
    public Tournament createTournament() {
        return new Tournament();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Tournament }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "models.repr", name = "Tournament")
    public JAXBElement<Tournament> createTournament(Tournament value) {
        return new JAXBElement<Tournament>(_Tournament_QNAME, Tournament.class, null, value);
    }

}
