//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.04 at 01:20:28 PM GMT 
//

@ae.javax.xml.bind.annotation.XmlSchema(namespace = "models.repr", elementFormDefault = ae.javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package repr.models;
